//Replace ’ '      “ ” \"    — -
// 1= beginning of question          1| end of question
export const verses = {
  book: {
    "romans": {
      chapter: {
        "1": {
          verse: { 
            "1": "1=Paul, a servant of 1| Christ Jesus, 2=called to be 2|an apostle and 3=set apart for 3|the gospel of God",
            "2": "1=the gospel 2=he 1| promised beforehand through his 2|prophets in the Holy Scriptures",
            "3": "regarding his Son, 1=who as to 1| his earthly life was a descendant of David,",
            "4": "1=and who through the Spirit of holiness was 1| appointed the Son of God 2=in power by his 2|resurrection from the dead: Jesus Christ our Lord.",
            "5": "1=Through him we received 1| grace and apostleship 2=to call all the Gentiles 3=to the 2|obedience that comes from 3|faith for his name's sake.",
            "6": "And 1=you are also among 1| those Gentiles called to belong to Jesus Christ.",
            "7": "1=To all in 1|Rome 2=who are loved by 2| God and called to be His holy people: 3=Grace and peace to 3|you from God our Father and from the Lord Jesus Christ.",
            "8": "First, I 1=thank my God through 1| Jesus Christ for all of you 2=because 3=your faith is being 2|reported 3|all over the world.",
            "9": "God, 1=whom I serve in my spirit in 1|preaching the gospel of his Son, 2=is my witness how 2|constantly I remember you",
            "10": "in my prayers at all times; 1=and I pray that now 1| at last 2=by God's will the way may be 2|opened for me to come to you.",
            "11": "1=I long to see you so that I 2=may 1|impart to you some 2|spiritual gift to make you strong=",
            "12": "that is, 1=that you and I 2=may be 1|mutually encouraged by 2|each other's faith.",
            "13": "I 1=do not want you to be unaware, brothers and sisters, that 1|I planned many times to come to you (but have been prevented from doing so until now) 2=in order that I might 2|have a harvest among you, 3=just as I have had among 3|the other Gentiles.",
            "14": "1=I am obligated both to 1|Greeks and non-Greeks, 2=both to the 2|wise and the foolish.",
            "15": "That is why 1=I am so eager 2=to 1|preach the gospel also 2|to you who are in Rome.",
            "16": "For I am not ashamed of the gospel, 1=because it is the power of God 1|that 2=brings salvation to everyone who believes:2| first to the Jew, then to the Gentile.",
            "17": "For in the gospel the righteousness of God is revealed- 1=a righteousness that is 1|by faith from first to last, 2=just as it is written: 2|\"The righteous will live by faith.\"",
            "18": "1=The wrath of God is being revealed against 1|all the godlessness and wickedness of people, 2=who suppress the truth 2|by their wickedness,",
            "19": "1=since 2=what may be known 1|about God is plain to them, 2|3=because God has made 3|it plain to them.",
            "20": "For since 1=the creation of the world God's 1|invisible qualities-his eternal power and divine nature-2=have been clearly seen, 2|3=being understood from 3|what has been made, so that people are without excuse.",
            "21": "For although they knew God, 1=they neither glorified him 1|as God nor gave thanks to him, 2=but their thinking became 2|futile and their foolish hearts were darkened.",
            "22": "1=Although they claimed 1|to be wise, they became fools",
            "23": "and 1=exchanged the glory of 1|the immortal God 2=for images made to look like 2|a mortal human being and birds and animals and reptiles.",
            "24": "1=Therefore God gave them over in the 1|2=sinful desires of their hearts to 2|sexual impurity for 3=the degrading 3|of their bodies with one another.",
            "25": "1=They exchanged the truth about God 1|for a lie, and 2=worshiped and served 3=created things 2|rather than 3|the Creator-who is forever praised. Amen.",
            "26": "Because of this, 1=God gave them over to 1|shameful lusts. 2=Even their women 3=exchanged 2|natural 3|sexual relations for unnatural ones.",
            "27": "In the same way 1=the men also abandoned 1|natural relations 2=with women and were 2|inflamed with lust for one another. Men 3=committed shameful acts with 3|other men, and 4=received in themselves the 4|due penalty for their error.",
            "28": "Furthermore, just as 1=they did not think it 1|worthwhile to retain the knowledge of God, so 2=God gave them over to 2|a depraved mind, so that they do what ought not to be done.",
            "29": "They have 1=become filled with every kind of 1|wickedness, evil, greed and depravity. 2=They are full of 2|envy, murder, strife, deceit and malice. They are gossips,",
            "30": "slanderers, God-haters, insolent, arrogant and boastful; 1=they invent ways of 1|doing evil; they disobey their parents;",
            "31": "1=they have no 1|understanding, no fidelity, no love, no mercy.",
            "32": "1=Although they know God's righteous decree that 1|those who do such things deserve death, 2=they not only continue to do 2|these very things 3=but also approve 3|of those who practice them."
          }
        },
        "2": { 
          verse: {
            "1": "1=You, therefore, 1|have no excuse, 2=you who pass 2|judgment on someone else, for 3=at whatever point you 3|judge another, you are condemning yourself, because 4=you who pass judgment do 4|the same things.",
            "2": "1=Now we know that 1|God's judgment against those who do such things is based on truth.",
            "3": "1=So when you, 1|a mere human being, 2=pass judgment on them and 2|yet do the same things, 3=do you think you will 3|escape God's judgment?",
            "4": "Or 1=do you show contempt for 1|the riches of his kindness, forbearance and patience, 2=not realizing that 2|God's kindness is intended to lead you to repentance?",
            "5": "1=But because of 1|your stubbornness and your unrepentant heart, 2=you are storing up wrath against 2|yourself for the day of God's wrath, when his righteous judgment will be revealed.",
            "6": "1=God \"will 1|repay each person according to what they have done.\"",
            "7": "1=To those who by 1|persistence in doing good seek glory, honor and immortality, he will give eternal life.",
            "8": "But 1=for those who are 1|self-seeking and 2=who reject the 2|truth and follow evil, there will be wrath and anger.",
            "9": "1=There will be trouble 1|and distress for every human being who does evil: first for the Jew, then for the Gentile;",
            "10": "but 1=glory, honor and 1|peace for everyone who does good: first for the Jew, then for the Gentile.",
            "11": "For 1=God does not 1|show favoritism.",
            "12": "1=All who sin apart 1|from the law will also perish apart from the law, and 2=all who sin under 2|the law will be judged by the law.",
            "13": "For 1=it is not those who 1|hear the law who are righteous in God's sight, but 2=it is those who 2|obey the law who will be declared righteous.",
            "14": "(Indeed, 1=when Gentiles, who 1|do not have the law, 2=do by nature 2|things required by the law, 3=they are a law for 3|themselves, even though 4=they do not have 4|the law.",
            "15": "1=They show that the requirements of 1|the law are written on their hearts, 2=their consciences 2|also bearing witness, and 3=their thoughts sometimes 3|accusing them and at other times even defending them.)",
            "16": "1=This will take place on 1|the day when 2=God judges people's 2|secrets through Jesus Christ, as my gospel declares.",
            "17": "Now you, 1=if you call yourself 1|a Jew; 2=if you rely on 2|the law and boast in God;",
            "18": "1=if you know his 1|will 2=and approve of what 2|is superior because you are instructed by the law;",
            "19": "1=if you are convinced that 1|you are a guide for the blind, 2=a light for 2|those who are in the dark,",
            "20": "1=an instructor of 1|the foolish, 2=a teacher of 2|little children, because 3=you have in the law the 3|embodiment of knowledge and truth-",
            "21": "1=you, then, who 1|teach others, do you not teach yourself? 2=You who preach against 2|stealing, do you steal?",
            "22": "1=You who say that people should not 1|commit adultery, do you commit adultery? 2=You who abhor 2|idols, do you rob temples?",
            "23": "1=You who boast in 1|the law, do you dishonor God by breaking the law?",
            "24": "1=As it is written: 1|\"God's name is blasphemed among the Gentiles because of you.\"",
            "25": "1=Circumcision has value if you 1|observe the law, but 2=if you break the law, 2|you have become as though you had not been circumcised.",
            "26": "So then, 1=if those who are not circumcised 1|keep the law's requirements, 2=will they not be regarded as though 2|they were circumcised?",
            "27": "1=The one who is not circumcised 1|physically and 2=yet obeys the law will 2|condemn you who, 3=even though you have 3|the written code and circumcision, are a lawbreaker.",
            "28": "1=A person is not a Jew who is 1|one only outwardly, 2=nor is circumcision merely 2|outward and physical.",
            "29": "No, 1=a person is a Jew who is one 1|inwardly; and 2=circumcision is circumcision of 2|the heart, by the Spirit, not by the written code. 3=Such a person's 3|praise is not from other people, but from God."
          }
        },
        "3": {
          verse: {
            "1": "1=What advantage, then, 1|is there in being a Jew, or 2=what value is there 2|in circumcision?",
            "2": "Much in every way! 1=First of all, 1|the Jews have been entrusted with the very words of God.",
            "3": "1=What if some were 1|unfaithful? 2=Will their unfaithfulness 2|nullify God's faithfulness?",
            "4": "Not at all! 1=Let God be 1|true, and 2=every human being a 2|liar. 3=As it is written: 3|\"So that you may be proved right when you speak and prevail when you judge.\"",
            "5": "But 1=if our unrighteousness 1|2=brings out God's 2|righteousness more clearly, what shall we say? That 3=God is unjust in 3|bringing his wrath on us? (4=I am using 4|a human argument.)",
            "6": "Certainly not! 1=If that were so, 1|how could God judge the world?",
            "7": "1=Someone might argue, 1|2=\"If my falsehood 2|enhances God's truthfulness 3=and so increases 3|his glory, 4=why am I still 4|condemned as a sinner?\"",
            "8": "1=Why not say-1|as some slanderously claim that we say-\"2=Let us do 2|evil that good may result\"? Their condemnation is just!",
            "9": "1=What shall we 1|conclude then? 2=Do we have 2|any advantage? Not at all! 4=For we have already made 4|the charge that Jews and Gentiles alike are all under the power of sin.",
            "10": "1=As it is written: 1|\"There is no one righteous, not even one;",
            "11": "1=there is no one who 1|understands; there is no one who seeks God.",
            "12": "1=All have 1|turned away, 2=they have together 2|become worthless; there is no one who does good, not even one.\"",
            "13": "1=\"Their throats are 1|open graves; their tongues practice deceit.\" 2=\"The poison 2|of vipers is on their lips.\"",
            "14": "1=Their mouths 1|are full of cursing and bitterness.\"",
            "15": "1=\"Their feet 1|are swift to shed blood;",
            "16": "1=ruin and 1|misery mark their ways,",
            "17": "and 1=the way of 1|peace they do not know.\"",
            "18": "1=\"There is no 1|fear of God before their eyes.\"",
            "19": "1=Now we know that 1|whatever the law says, 2=it says to those 2|who are under the law, 3=so that every 3|mouth may be silenced and the whole world held accountable to God.",
            "20": "1=Therefore no one will 1|be declared righteous in God's sight by the works of the law; 2=rather, through 2|the law we become conscious of our sin.",
            "21": "But 1=now apart from 1|the law the righteousness of God has been made known, 2=to which the Law 2|and the Prophets testify.",
            "22": "1=This righteousness is given 1|through faith in Jesus Christ to all who believe. 2=There is no 2|difference between Jew and Gentile,",
            "23": "1=for all have 1|sinned and fall short of the glory of God,",
            "24": "1=and all are 1|justified freely by his grace through the redemption that came by Christ Jesus.",
            "25": "1=God presented Christ as 1|a sacrifice of atonement, 2=through the shedding of 2|his blood-to be received by faith. 3=He did this to 3|demonstrate his righteousness, because 4=in his forbearance he 4|had left the sins committed beforehand unpunished-",
            "26": "1=he did it to 1|demonstrate his righteousness at the present time, 2=so as to be 2|just and the one who justifies those who have faith in Jesus.",
            "27": "1=Where, then, is boasting? 1|It is excluded. 2=Because of what law? 2|The law that requires works? No, because of the law that requires faith.",
            "28": "For 1=we maintain that 1|a person is justified by faith apart from the works of the law.",
            "29": "Or 1=is God the God 1|of Jews only? 2=Is he not the 2|God of Gentiles too? Yes, of Gentiles too,",
            "30": "1=since there is 1|only one God, 2=who will justify 2|the circumcised by faith and the uncircumcised through that same faith.",
            "31": "1=Do we, then, 1|nullify the law by this faith? Not at all! 2=Rather, we 2|uphold the law."
          }
        },
        "4": {
          verse: {
            "1": "1=What then 1|2=shall we 2|say that 3=Abraham, our 3|forefather 4=according to 4|the flesh, 5=discovered in 5|this matter?",
            "2:": "1=If, 1|in fact, 2=Abraham was 2|justified by works, 3=he had something to 3|boast about-4=but not 4|before God.",
            "3": "1=What does 1|Scripture say? \"Abraham believed God, and it was credited to him as righteousness.\"",
            "4": "1=Now to 1|the one who works, 2=wages are not 2|credited as a gift 3=but as 3|an obligation.",
            "5": "1=However, 1|2=to the one who 2|does not work 3=but trusts 3|God who justifies the ungodly, 4=their faith is 4|credited as righteousness.",
            "6": "1=David says 1|the same thing when 2=he speaks of 2|the blessedness of the one to whom God credits righteousness apart from works:",
            "7": "1=\"Blessed are 1|those whose transgressions are forgiven, whose sins are covered.",
            "8": "1=Blessed is 1|the one whose sin the Lord will never count against them.\"",
            "9": "1=Is this blessedness 1|only for the circumcised, 2=or also for 2|the uncircumcised? 3=We have been saying that 3|Abraham's faith was credited to him as righteousness.",
            "10": "1=Under what 1|circumstances was it credited? 2=Was it after he was 2|circumcised, or before? 3=It was not 3|after, but before!",
            "11": "1=And he received 1|circumcision as a sign, 2=a seal of 2|the righteousness that 3=he had by 3|faith while he was still uncircumcised. 4=So then, 4|he is the father of all who believe but have not been circumcised, 5=in order that 5|righteousness might be credited to them.",
            "12": "1=And he is then also 1|the father of the circumcised who not only are circumcised 2=but who also 2|follow in the footsteps of the faith that 3=our father 3|Abraham had before he was circumcised.",
            "13": "1=It was not through 1|the law that Abraham and his offspring received the promise that he would be heir of the world, 2=but through 2|the righteousness that comes by faith.",
            "14": "1=For if those who 1|depend on the law are heirs, 2=faith means 2|nothing and the promise is worthless,",
            "15": "1=because 1|the law brings wrath. 2=And where 2|there is no law there is no transgression.",
            "16": "1=Therefore, 1|the promise comes by faith, 2=so that it 2|may be by grace 3=and may be 3|guaranteed to all Abraham's offspring-4=not only to 4|those who are of the law but 5=also to those who 5|have the faith of Abraham. 6=He is 6|the father of us all.",
            "17": "1=As it is written: 1|\"I have made you a father of many nations.\" He is our father in the sight of God, in whom he believed-the God who gives life to the dead and calls into being things that were not.",
            "18": "1=Against all hope, 1|Abraham in hope believed and so became the father of many nations, 2=just as 2|it had been said to him, \"So shall your offspring be.\"",
            "19": "1=Without 1|weakening in his faith, he faced the fact that his body was as good as dead-2=since he was 2|about a hundred years old-3=and that 3|Sarah's womb was also dead.",
            "20": "1=Yet he did 1|not waver through unbelief regarding the promise of God, 2=but was 2|strengthened in his faith and gave glory to God,",
            "21": "1=being 1|fully persuaded that 2=God had 2|power to do what he had promised.",
            "22": "1=This is why 1|\"it was credited to him as righteousness.\"",
            "23": "1=The words 1|\"it was credited to him\" were written not for him alone,",
            "24": "1=but also for 1|us, 2=to whom 2|God will credit righteousness-for us who believe in him who raised Jesus our Lord from the dead.",
            "25": "1=He was 1|delivered over to death for our sins and was raised to life for our justification."
          }
        }
      }
    },
    "james": {
      chapter: {
        "1": {
          verse: {
            "1": "1=James, a servant of 1|God and of the Lord Jesus Christ, 2=To the twelve tribes 2|scattered among the nations: Greetings.",
            "2": "1=Consider it pure joy, my brothers and sisters, 1|whenever you face trials of many kinds,",
            "3": "because 1=you know that the testing of 1|your faith produces perseverance.",
            "4": "Let 1=perseverance finish its work 2=so 1|that you may be 2|mature and complete, not lacking anything.",
            "5": "If any of you lacks wisdom, you should ask God, 1=who gives generously 1|to all without finding fault, and it will be given to you.",
            "6": "1=But when you ask, you must 1|believe and not doubt, because 2=the one who doubts is like 2|a wave of the sea, blown and tossed by the wind.",
            "7": "1=That person should not expect to 1|receive anything from the Lord.",
            "8": "1=Such a person is 1|double minded and unstable in all they do.",
            "9": "1=Believers in humble circumstances 1|ought to take pride in their high position.",
            "10": "1=But the rich should 1|take pride in their humiliation 2=since they will pass away like a 2|wild flower",
            "11": "For 1=the sun rises with 1|scorching heat and withers the plant; 2=its blossom falls and 2|its beauty is destroyed. 3=In the same way, the rich will 3|fade away even while they go about their business.",
            "12": "1=Blessed is the one who perseveres under trial because, 1|having stood the test, 2=that person will receive the crown of life that 2|the Lord has promised to those who love him.",
            "13": "When tempted, 1=no one should say, 1|\"God is tempting me.\" For God cannot be tempted by evil, nor does he tempt anyone;",
            "14": "but 1=each person is tempted when 1|2=they are dragged away by 2|their own evil desire and enticed.",
            "15": "Then, 1=after desire has conceived, it gives birth 1|to sin; and sin, when it is full-grown, gives birth to death.",
            "16": "1=Don't be deceived 1|, my dear brothers and sisters.",
            "17": "1=Every good and perfect gift is from 1|above, 2=coming down from 2|the Father of the heavenly lights, 3=who does not change 3|like shifting shadows.",
            "18": "1=He chose to give us 1|birth through the word of truth, 2=that we might be a kind of 2|firstfruits of all he created.",
            "19": "1=My dear brothers and sisters, 1|take note of this: 2=Everyone should be 2|quick to listen, slow to speak and slow to become angry,",
            "20": "because 1=human anger does not 1|produce the righteousness that God desires.",
            "21": "Therefore, 1=get rid of all moral filth and 1|the evil that is so prevalent and 2=humbly accept the 2|word planted in you, which can save you.",
            "22": "1=Do not merely listen to 1|the word, and so deceive yourselves. Do what it says.",
            "23": "Anyone 1=who listens to the 1|word but does not do what it says 2=is like someone who 2|looks at his face in a mirror",
            "24": "and, 1=after looking at himself, 1|goes away and immediately forgets what he looks like.",
            "25": "But 1=whoever looks intently into |the perfect law that gives freedom, and continues in it, 2=not forgetting what they 2|have heard, but doing it; 3=they will be blessed 3|in what they do.",
            "26": "1=Those who consider themselves 1|religious and 2=yet do not keep a 2|tight rein on their tongues deceive themselves, and 3=their religion is 3|worthless.",
            "27": "1=Religion that God our Father accepts as 1|pure and faultless is this: 2=to look after 2|orphans and widows in their distress 3=and to keep 3|oneself from being polluted by the world."
          }
        },
        "2": {
          verse: {
            "1": "1=My brothers and sisters, believers 1|in our glorious 2=Lord Jesus Christ must 2|not show favoritism.",
            "2": "1=Suppose a man comes 1|into 2=your meeting wearing 2|a gold ring and fine clothes, and a poor man in filthy old clothes also comes in.",
            "3": "1=If you show special attention to 1|the man wearing fine clothes and say, \"Here's a good seat for you,\" 2=but say to 2|the poor man, \"You stand there\" or \"Sit on the floor by my feet,\"",
            "4": "1=have you not 1|discriminated among yourselves and become judges with evil thoughts?",
            "5": "Listen, my dear brothers and sisters: 1=Has not God chosen 1|those who are poor 1=in the eyes of the world to be 1|rich in faith and to inherit the kingdom he promised those who love him?",
            "6": "1=But you have dishonored 1|the poor. 2=Is it not the rich 2|who are exploiting you? 3=Are they not the ones who are 3|dragging you into court?",
            "7": "1=Are they not the ones who are 1|blaspheming the noble name of him to whom you belong?",
            "8": "If you 1=really keep the royal 1|law found in Scripture, \"Love your neighbor as yourself,\" you are doing right.",
            "9": "But 1=if you show favoritism 1|, 2=you sin and are 2|convicted by the law as lawbreakers.",
            "10": "For 1=whoever keeps the whole law and 2=yet 1|stumbles at 2|just one point is guilty of breaking all of it.",
            "11": "1=For he who said, \"You shall not 1|commit adultery,\" also said, \"You shall not murder.\" 2=If you do not commit adultery but do2| commit murder, you have become a lawbreaker.",
            "12": "1=Speak and act as those who are 1|going to be judged by the law that gives freedom,",
            "13": "because 1=judgment without mercy will be shown 1|to anyone who has not been merciful. Mercy triumphs over judgment.",
            "14": "1=What good is it, my brothers and sisters, 2=if someone 1|claims to have 2|faith but has no deeds? Can such faith save them?",
            "15": "Suppose 1=a brother or a sister is without 1|clothes and daily food.",
            "16": "1=If one of you says 1|to them, \"Go in peace; keep warm and well fed,\" but 2=does nothing about 2|their physical needs, what good is it?",
            "17": "In the same way, 1=faith by itself, if 1|it is not accompanied by action, is dead.",
            "18": "But 1=someone will say, 1|\"You have faith; I have deeds.\" 2=Show me your faith without 2|deeds, and I will show you my faith by my deeds.",
            "19": "1=You believe that there is 1|one God. Good! Even the demons believe that= and shudder.",
            "20": "You foolish person, 1=do you want evidence that 1|faith without deeds is useless?",
            "21": "Was not 1=our father Abraham considered 1|righteous for what he did 2=when he offered his 2|son Isaac on the altar?",
            "22": "You see that 1=his faith and his 1|actions were working together, and 2=his faith was made 2|complete by what he did.",
            "23": "And 1=the scripture was fulfilled that says, 1|\"Abraham believed God, and 2=it was credited to him as 2|righteousness,\" and he was called God's friend.",
            "24": "You see that 1=a person is considered righteous 1|by what they do and not by faith alone.",
            "25": "In the same way, 1=was not even Rahab the prostitute considered 1|righteous 2=for what she did when she gave 2|lodging to the spies and sent them off in a different direction?",
            "26": "1=As the body without 1|the spirit is dead, so faith without deeds is dead."
          }
        },
        "3": {
          verse: {
            "1": "1=Not many of you should become 1|teachers, my fellow believers, because 2=you know 2|that we who teach 3=will be judged 3|more strictly.",
            "2": "We 1=all stumble 1|in many ways. Anyone who is 2=never at 2|fault in what they say is perfect, able 3=to keep their 3|whole body in check.",
            "3": "When 1=we put 1|bits into the mouths of horses 2=to make them 2|obey us, 3=we can turn 3|the whole animal.",
            "4": "1=Or take 1|ships as an example. 2=Although 2|they are so large and are driven by strong winds, 3=they are steered 3|by a very small rudder 4=wherever 4|the pilot wants to go.",
            "5": "1=Likewise, 1|the tongue is a small part of the body, but 2=it makes 2|great boasts. Consider 3=what a great 3|forest is 4=set on fire 4|by a small spark.",
            "6": "1=The tongue also 1|is a fire, 2=a world of 2|evil among the parts of the body. 3=It corrupts 3|the whole body, sets the whole course of one's life on fire, and is itself set on fire by hell.",
            "7": "1=All kinds of 1|animals, birds, reptiles and sea creatures are being tamed and have been tamed by mankind,",
            "8": "but 2-no human 2|being can tame the tongue. 3=It is 3|a restless evil, full of deadly poison.",
            "9": "1=With the tongue we 1|praise our Lord and Father, and 2=with it we 2|curse human beings, who have been made in God's likeness.",
            "10": "1=Out of the same 1|mouth come praise and cursing. 2=My brothers and sisters, 2|this should not be.",
            "11": "1=Can both 1|fresh water and salt water 2=flow from 2|the same spring?",
            "12": "My brothers and sisters, 1=can a 1|fig tree bear olives, or a 2=grapevine bear 2|figs? 3=Neither can 3|a salt spring produce fresh water.",
            "13": "1=Who is wise 1|and understanding among you? 2=Let them show it by 2|their good life, 3=by deeds done in 3|the humility that comes from wisdom.",
            "14": "But 1=if you harbor 1|bitter envy and selfish ambition in your hearts, 1=do not boast 1|about it or deny the truth.",
            "15": "Such \"wisdom\" 1=does not come down from 1|heaven but is earthly, unspiritual, demonic.",
            "16": "For 1=where you have 1|envy and selfish ambition, 2=there you find 2|disorder and every evil practice.",
            "17": "But the wisdom that comes from heaven is 1=first of all 1|pure; then peace-loving, considerate, submissive, 2=full of 2|mercy and good fruit, impartial and sincere.",
            "18": "Peacemakers 1=who sow in 1|peace reap a harvest of righteousness."
          }
        },
        "4": {
          verse: {
            "1": "What 1=causes fights 1|and quarrels among you? Don't 2=they come 2|from your 3=desires that 3|battle within you?",
            "2": "1=You desire 1|but do not have, so you kill. You covet but you 2=cannot get 2|what you want, so you quarrel and fight. You do not have because 3=you do not ask 3|God.",
            "3": "When you ask, 1=you do not receive, 1|because you ask with wrong motives, that 2=you may spend 2|what you get on your pleasures.",
            "4": "1=You adulterous people, 1|don't you know that 2=friendship with 2|the world means enmity against God? Therefore, 3=anyone who chooses 3|to be a friend of the world becomes an enemy of God.",
            "5": "Or do you think 1=Scripture says 1|without reason that he jealously 2=longs for 2|the spirit he has caused to dwell in us?",
            "6": "But 1=he gives 1|us more grace. That is why 2=Scripture says: 2|\"God opposes the proud but shows favor to the humble.\"",
            "7": "1=Submit 1|yourselves, then, to God. 2=Resist 2|the devil, and he will flee from you.",
            "8": "1=Come near 1|to God and he will come near to you. Wash 2=your hands, 2|you sinners, and purify your hearts, you double-minded.",
            "9": "1=Grieve, 1|mourn and wail. 2=Change your 2|laughter to mourning and your joy to gloom.",
            "10": "Humble yourselves before the Lord, and he will lift you up.",
            "11": "Brothers and sisters, 1=do not slander 1|one another. 2=Anyone who speaks 2|against a brother or sister or judges them speaks against the law and judges it. 3=When you judge 3|the law, you are not keeping it, but sitting in judgment on it.",
            "12": "1=There is only one 1|Lawgiver and Judge, the one 2=who is able to 2|save and destroy. 3=But you - 3|who are you to judge your neighbor?",
            "13": "Now listen, 1=you who say, 1|\"Today or tomorrow we will go to this or that city, spend a year there, carry on business and make money.\"",
            "14": "Why, 1=you do not even know 1|what will happen tomorrow. What is your life? 2=You are a 2|mist that appears for a little while and then vanishes.",
            "15": "Instead, 1=you ought to say, 1|\"If it is the Lord's will, we will live and do this or that.\"",
            "16": "As it is, 1=you boast in 1|your arrogant schemes. All such boasting is evil.",
            "17": "1=If anyone, then, 1|2=knows the 2|good 3=they ought to 3|do and doesn't do it, it is sin for them."
          }
        },
        "5": {
          verse: {
            "1": "1=Now listen, 1|you rich people, 2=weep and 2|wail because of the misery that is coming on you.",
            "2": "1=Your wealth 1|has rotted, and moths have eaten your clothes.",
            "3": "1=Your gold and 1|silver are corroded. Their corrosion 2=will testify 2|against you and eat your flesh like fire. 1=You have hoarded 1|wealth in the last days.",
            "4": "Look! 1=The wages you 1|failed to pay the workers who mowed your fields are crying out against you. 2=The cries of 2|the harvesters have reached the ears of the Lord Almighty.",
            "5": "1=You have lived 1|on earth in luxury and self-indulgence. 2=You have fattened 2|yourselves in the day of slaughter.",
            "6": "1=You have condemned 1|and murdered the innocent one, who was not opposing you.",
            "7": "1=Be patient, 1|then, brothers and sisters, 2=until 2|the Lord's coming. 3=See how 3|the farmer waits for the land to 4=yield its 4|valuable crop, patiently 5=waiting for 5|the autumn and spring rains.",
            "8": "You too, 1=be patient and 1|stand firm, because the 2=Lord's coming 2|is near.",
            "9": "1=Don't grumble 1|against one another, brothers and sisters, or 2=you will be 2|judged. 3=The Judge 3|is standing at the door!",
            "10": "Brothers and sisters, 1=as an example of 1|patience in the face of suffering, 2=take the 2|prophets who spoke in the name of the Lord.",
            "11": "As you know, 1=we count as 1|blessed those who have persevered. 2=You have heard of 2|Job's perseverance and have seen what the Lord finally brought about. 3=The Lord is 3|full of compassion and mercy.",
            "12": "Above all, 1=my brothers and sisters, do not 1|swear-not by heaven or by earth or by anything else. All you need to say is a simple \"Yes\" or \"No.\" Otherwise you will be condemned.",
            "13": "1=Is anyone among you in 1|trouble? Let them pray. 2=Is anyone 2|happy? Let them sing songs of praise.",
            "14": "1=Is anyone among you 1|sick? Let them call the elders 2=of the church to 2|pray over them and anoint them with oil in the name of the Lord.",
            "15": "And 1=the prayer offered in 1|faith will make the sick person well; the Lord will raise them up. 2=If they have 2|sinned, they will be forgiven.",
            "16": "Therefore 1=confess your sins to 1|each other and pray for each other so that you may be healed. The 2=prayer of a 2|righteous person is powerful and effective.",
            "17": "Elijah was a human being, even as we are. 1=He prayed earnestly 1|that it would not rain, and it did not rain on the land for three and a half years.",
            "18": "Again he prayed, and 1=the heavens gave 1|rain, and the earth produced its crops.",
            "19": "My brothers and sisters, 1=if one of you should 1|wander from the truth and someone should bring that person back,",
            "20": "remember this: 1=Whoever turns a 1|sinner from the error of their way 2=will save them from 2|death and cover over a multitude of sins."
          }
        }
      }
    }
  }
}
